---
abstract: 'HTTP keep-alive support'
author:
  - 'Philip Gwyn <gwyn -at- cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-HTTP-KeepAlive
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Request: 0
  HTTP::Response: 0
  HTTP::Status: 0
  LWP::UserAgent: 6
  POE: 1.311
version: 0.0307
